services:
  reactive-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamoney-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    user: rn_dev
    networks:
      - mamoney-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5037:5037"
      - "8081:8080"
    # ✅ Keep container running & allow interactive shell
    stdin_open: true
    tty: true

networks:
  mamoney-network:
    driver: bridge
