// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKu2IJ-IyxRViG9z0JfI4SPBbdEIA6Kg',
    appId: '1:144454845536:web:e59cd7ad218df3a8d86f05',
    messagingSenderId: '144454845536',
    projectId: 'mamo1-16064',
    authDomain: 'mamo1-16064.firebaseapp.com',
    storageBucket: 'mamo1-16064.firebasestorage.app',
    measurementId: 'G-6LNBNEKELC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHSmiWVzazdgAs1Px3zDIJwEZk_mx1f0',
    appId: '1:144454845536:ios:4ed7469349d814bad86f05',
    messagingSenderId: '144454845536',
    projectId: 'mamo1-16064',
    storageBucket: 'mamo1-16064.firebasestorage.app',
    iosBundleId: 'com.example.mamoney',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpm-IgCu3F1rS6fXYRt1AJSiGGvWc0FgY',
    appId: '1:144454845536:android:4bc36b90ad55918ed86f05',
    messagingSenderId: '144454845536',
    projectId: 'mamo1-16064',
    storageBucket: 'mamo1-16064.firebasestorage.app',
  );

}